### ISSUE TITLE
Replace icon

### ISSUE THREAD

**Issue by ashledombos** [vikhyat/discourse-persona#2]
Hello,

would it be possible to replace "]" by this fontawesome glyph?

http://fortawesome.github.io/Font-Awesome/icon/user/

here in plugin.rb

```
.btn-social.persona:before {
  content: "]";
}
```

(or even nothing if it's easier :)

Raphaël

**Comment by vikhyat** [comment]
I got rid of the icon. PR to add a FontAwesome glyph in its place would be welcome but I don't have the time to add it right now.

**Comment by ashledombos** [comment]
Thanks :) I'll make a feture request if I find a nice solution.
